{% set name = "Keras-Preprocessing" %}
{% set version = "1.1.1" %}
# {% set sha256 = "138012da7bbc5508d59681515636c01618644322db08c1f4c6d66e63de8ddb73" %}
{% set sha256 = "c0b1ebe444e46075a9079629fa0e0d0fb1d681b4a72340ca5406b574894276a5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/py2.py3/K/Keras-Preprocessing/Keras_Preprocessing-{{version}}-py2.py3-none-any.whl
  url: https://pypi.io/packages/source/K/Keras-Preprocessing/Keras_Preprocessing-{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.9.1
    - scipy >=0.14
    - six >=1.9.0
  # avoid a direct requirement on keras to prevent a circular dependency
  run_constrained:
    - keras >=2.1.6

test:
  imports:
    - keras_preprocessing

about:
  home: https://github.com/keras-team/keras-preprocessing
  license: MIT 
  license_family: MIT
  license_file: LICENSE
  summary: Data preprocessing and data augmentation module of the Keras deep learning library
  description: |
    Keras Preprocessing is the data preprocessing and data augmentation module
    of the Keras deep learning library. It provides utilities for working
    with image data, text data, and sequence data.
  doc_url: https://keras.io/
  dev_url: https://github.com/keras-team/keras-preprocessing

extra:
  recipe-maintainers:
    - CurtLH
    - jjhelmus
